// Auto-generated by scripts/scrape-apps.mjs — 2026-04-25T23:16:43.728Z
// Do not edit manually. Run: node scripts/scrape-apps.mjs

export interface AppEntry {
  id: string;
  name: string;
  category: string;
  icon: string;
  rating: number;
  reviews: number;
  downloads: string;
  pain: number;
  trend: string;
}

export const SCRAPED_APPS: AppEntry[] = [
  {
    "id": "com.larus.wolf",
    "name": "Dola: assist. inteligente (IA)",
    "category": "Produtividade",
    "icon": "/apps/dola-assist-inteligente-ia.png",
    "rating": 4.3,
    "reviews": 577581,
    "downloads": "100M+",
    "pain": 34,
    "trend": "—"
  },
  {
    "id": "com.openai.chatgpt",
    "name": "ChatGPT",
    "category": "Produtividade",
    "icon": "/apps/chatgpt.png",
    "rating": 4.8,
    "reviews": 44428571,
    "downloads": "1.0B+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.google.android.apps.bard",
    "name": "Google Gemini",
    "category": "Produtividade",
    "icon": "/apps/google-gemini.png",
    "rating": 4.7,
    "reviews": 33464475,
    "downloads": "1.0B+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.gov.dataprev.meuinss",
    "name": "Meu INSS – Central de Serviços",
    "category": "Produtividade",
    "icon": "/apps/meu-inss-central-de-servi-os.png",
    "rating": 4.8,
    "reviews": 4279408,
    "downloads": "50M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.facebook.stella",
    "name": "Meta AI - Assistente e óculos",
    "category": "Produtividade",
    "icon": "/apps/meta-ai-assistente-e-culos.png",
    "rating": 4.8,
    "reviews": 1319777,
    "downloads": "50M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.nu.production",
    "name": "Nubank: conta, cartão e mais",
    "category": "Finanças",
    "icon": "/apps/nubank-conta-cart-o-e-mais.png",
    "rating": 4.8,
    "reviews": 5516054,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.mercadopago.wallet",
    "name": "Mercado Pago: banco digital",
    "category": "Finanças",
    "icon": "/apps/mercado-pago-banco-digital.png",
    "rating": 4.9,
    "reviews": 12999345,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.picpay",
    "name": "Banco PicPay: Cartão, Pix e +",
    "category": "Finanças",
    "icon": "/apps/banco-picpay-cart-o-pix-e.png",
    "rating": 4.6,
    "reviews": 2629404,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.gov.caixa.tem",
    "name": "CAIXA Tem",
    "category": "Finanças",
    "icon": "/apps/caixa-tem.png",
    "rating": 4.2,
    "reviews": 5863011,
    "downloads": "100M+",
    "pain": 37,
    "trend": "—"
  },
  {
    "id": "io.cloudwalk.infinitepaydash",
    "name": "InfinitePay Tap, Conta, Cartão",
    "category": "Finanças",
    "icon": "/apps/infinitepay-tap-conta-cart-o.png",
    "rating": 4.8,
    "reviews": 810899,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.strava",
    "name": "Strava: corrida, pedal, trilha",
    "category": "Saúde & Fitness",
    "icon": "/apps/strava-corrida-pedal-trilha.png",
    "rating": 4.8,
    "reviews": 1103709,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "app.befit",
    "name": "Befit: Plano e Treino Academia",
    "category": "Saúde & Fitness",
    "icon": "/apps/befit-plano-e-treino-academia.png",
    "rating": 4.6,
    "reviews": 2813,
    "downloads": "500K+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.bloodsugar.diabetes.tracker.pro",
    "name": "Monitor de Glicose e Diabetes",
    "category": "Saúde & Fitness",
    "icon": "/apps/monitor-de-glicose-e-diabetes.png",
    "rating": 4.5,
    "reviews": 11041,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.totalpassmobile",
    "name": "TotalPass: fitness e bem-estar",
    "category": "Saúde & Fitness",
    "icon": "/apps/totalpass-fitness-e-bem-estar.png",
    "rating": 4.9,
    "reviews": 251049,
    "downloads": "5M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "org.iggymedia.periodtracker",
    "name": "Calendário Menstrual Flo",
    "category": "Saúde & Fitness",
    "icon": "/apps/calend-rio-menstrual-flo.png",
    "rating": 4.9,
    "reviews": 4869993,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.sankuai.sailor.afooddelivery",
    "name": "Keeta - Delivery de comida",
    "category": "Alimentação",
    "icon": "/apps/keeta-delivery-de-comida.png",
    "rating": 4.4,
    "reviews": 202141,
    "downloads": "10M+",
    "pain": 33,
    "trend": "—"
  },
  {
    "id": "br.com.brainweb.ifood",
    "name": "iFood comida e mercado em casa",
    "category": "Alimentação",
    "icon": "/apps/ifood-comida-e-mercado-em-casa.png",
    "rating": 4.7,
    "reviews": 13426127,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "burgerking.com.br.appandroid",
    "name": "Burger King Brasil",
    "category": "Alimentação",
    "icon": "/apps/burger-king-brasil.png",
    "rating": 4.9,
    "reviews": 733206,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.mcdo.mcdonalds",
    "name": "McDonald’s: Cupons e Delivery",
    "category": "Alimentação",
    "icon": "/apps/mcdonald-s-cupons-e-delivery.png",
    "rating": 4.4,
    "reviews": 1745062,
    "downloads": "100M+",
    "pain": 32,
    "trend": "—"
  },
  {
    "id": "com.cerveceriamodelo.modelonow",
    "name": "Zé Delivery",
    "category": "Alimentação",
    "icon": "/apps/z-delivery.png",
    "rating": 4.9,
    "reviews": 1670637,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.airbnb.android",
    "name": "Airbnb",
    "category": "Viagem",
    "icon": "/apps/airbnb.png",
    "rating": 4.8,
    "reviews": 1891897,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.gm.decolar",
    "name": "Decolar: Voos e Hotéis",
    "category": "Viagem",
    "icon": "/apps/decolar-voos-e-hot-is.png",
    "rating": 4.8,
    "reviews": 332304,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.comuto",
    "name": "BlaBlaCar: Ônibus e Caronas",
    "category": "Viagem",
    "icon": "/apps/blablacar-nibus-e-caronas.png",
    "rating": 4.9,
    "reviews": 2532185,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.clickbus.mobile",
    "name": "ClickBus - Passagens de ônibus",
    "category": "Viagem",
    "icon": "/apps/clickbus-passagens-de-nibus.png",
    "rating": 4.8,
    "reviews": 290093,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.latam.xp",
    "name": "LATAM: Voos, Hotéis, Carros",
    "category": "Viagem",
    "icon": "/apps/latam-voos-hot-is-carros.png",
    "rating": 4.9,
    "reviews": 419379,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.hellosimply.simplydraw",
    "name": "Simply Draw: Aprenda desenhar",
    "category": "Educação",
    "icon": "/apps/simply-draw-aprenda-desenhar.png",
    "rating": 4.6,
    "reviews": 117637,
    "downloads": "1M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.picoai.languageapp.android",
    "name": "Language Learning: Pingo AI",
    "category": "Educação",
    "icon": "/apps/language-learning-pingo-ai.png",
    "rating": 4.6,
    "reviews": 114931,
    "downloads": "1M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.duolingo",
    "name": "Duolingo: Inglês e muito mais!",
    "category": "Educação",
    "icon": "/apps/duolingo-ingl-s-e-muito-mais.png",
    "rating": 4.8,
    "reviews": 44939954,
    "downloads": "500M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "co.thewordlab.luzia",
    "name": "Luzia: Assistente Virtual IA",
    "category": "Educação",
    "icon": "/apps/luzia-assistente-virtual-ia.png",
    "rating": 4.5,
    "reviews": 127430,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "ai.praktika.android",
    "name": "Aprenda e fale inglês Praktika",
    "category": "Educação",
    "icon": "/apps/aprenda-e-fale-ingl-s-praktika.png",
    "rating": 4.8,
    "reviews": 1155553,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.zhiliaoapp.musically.go",
    "name": "TikTok Lite - Séries Curtas",
    "category": "Social",
    "icon": "/apps/tiktok-lite-s-ries-curtas.png",
    "rating": 4.3,
    "reviews": 10838137,
    "downloads": "1.0B+",
    "pain": 33,
    "trend": "—"
  },
  {
    "id": "com.zhiliaoapp.musically",
    "name": "TikTok",
    "category": "Social",
    "icon": "/apps/tiktok.png",
    "rating": 4.4,
    "reviews": 68707202,
    "downloads": "1.0B+",
    "pain": 32,
    "trend": "—"
  },
  {
    "id": "com.instagram.android",
    "name": "Instagram",
    "category": "Social",
    "icon": "/apps/instagram.png",
    "rating": 4.5,
    "reviews": 167415309,
    "downloads": "5.0B+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.instagram.lite",
    "name": "Instagram Lite",
    "category": "Social",
    "icon": "/apps/instagram-lite.png",
    "rating": 4,
    "reviews": 2513328,
    "downloads": "500M+",
    "pain": 40,
    "trend": "—"
  },
  {
    "id": "com.facebook.katana",
    "name": "Facebook",
    "category": "Social",
    "icon": "/apps/facebook.png",
    "rating": 4.8,
    "reviews": 180883728,
    "downloads": "10.0B+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.shopee.br",
    "name": "Shopee: 5.5 Moda & Beleza",
    "category": "Compras",
    "icon": "/apps/shopee-5-5-moda-beleza.png",
    "rating": 4.8,
    "reviews": 7221557,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.einnovation.temu",
    "name": "Temu: Compre como bilionário",
    "category": "Compras",
    "icon": "/apps/temu-compre-como-bilion-rio.png",
    "rating": 4.6,
    "reviews": 11652122,
    "downloads": "1.0B+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.zzkko",
    "name": "SHEIN-Compras Online",
    "category": "Compras",
    "icon": "/apps/shein-compras-online.png",
    "rating": 4.8,
    "reviews": 8610875,
    "downloads": "500M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.mercadolibre",
    "name": "Mercado Livre",
    "category": "Compras",
    "icon": "/apps/mercado-livre.png",
    "rating": 4.9,
    "reviews": 24812409,
    "downloads": "500M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.com.meliuz",
    "name": "Méliuz: Cashback e Nota Fiscal",
    "category": "Compras",
    "icon": "/apps/m-liuz-cashback-e-nota-fiscal.png",
    "rating": 4.7,
    "reviews": 1171837,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.microsoft.teams",
    "name": "Microsoft Teams",
    "category": "Negócios",
    "icon": "/apps/microsoft-teams.png",
    "rating": 4.8,
    "reviews": 8577927,
    "downloads": "500M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.app99.driver",
    "name": "99 Motorista e Entregador",
    "category": "Negócios",
    "icon": "/apps/99-motorista-e-entregador.png",
    "rating": 4.2,
    "reviews": 426304,
    "downloads": "10M+",
    "pain": 35,
    "trend": "—"
  },
  {
    "id": "fly.viewpdf.com",
    "name": "FLY PDF-View PDF",
    "category": "Negócios",
    "icon": "/apps/fly-pdf-view-pdf.png",
    "rating": 4.3,
    "reviews": 1639,
    "downloads": "1M+",
    "pain": 35,
    "trend": "—"
  },
  {
    "id": "br.com.ifood.driver.app",
    "name": "iFood para Entregadores",
    "category": "Negócios",
    "icon": "/apps/ifood-para-entregadores.png",
    "rating": 4.7,
    "reviews": 891533,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.coop.unimed.app",
    "name": "Unimed",
    "category": "Negócios",
    "icon": "/apps/unimed.png",
    "rating": 3.1,
    "reviews": 4280,
    "downloads": "1M+",
    "pain": 59,
    "trend": "—"
  },
  {
    "id": "com.freereels.app",
    "name": "FreeReels - Dramas & Reels",
    "category": "Entretenimento",
    "icon": "/apps/freereels-dramas-reels.png",
    "rating": 4.8,
    "reviews": 1198976,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.netshort.abroad",
    "name": "NetShort -  Séries Populares",
    "category": "Entretenimento",
    "icon": "/apps/netshort-s-ries-populares.png",
    "rating": 4.5,
    "reviews": 1082496,
    "downloads": "50M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.ss.android.ttmd.video",
    "name": "PineDrama - Séries Curtas",
    "category": "Entretenimento",
    "icon": "/apps/pinedrama-s-ries-curtas.png",
    "rating": 4.7,
    "reviews": 51307,
    "downloads": "10M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.newleaf.app.android.victor",
    "name": "ReelShort - Stream Drama & TV",
    "category": "Entretenimento",
    "icon": "/apps/reelshort-stream-drama-tv.png",
    "rating": 4.6,
    "reviews": 1551508,
    "downloads": "100M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "shorts.drama.video",
    "name": "Sua Novela - Drama Grátis",
    "category": "Entretenimento",
    "icon": "/apps/sua-novela-drama-gr-tis.png",
    "rating": 4.6,
    "reviews": 17065,
    "downloads": "5M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.gov.datasus.cnsdigital",
    "name": "Meu SUS Digital",
    "category": "Medicina",
    "icon": "/apps/meu-sus-digital.png",
    "rating": 3.8,
    "reviews": 230543,
    "downloads": "10M+",
    "pain": 44,
    "trend": "—"
  },
  {
    "id": "br.com.doctoralia",
    "name": "Doctoralia: agende seu médico",
    "category": "Medicina",
    "icon": "/apps/doctoralia-agende-seu-m-dico.png",
    "rating": 4.9,
    "reviews": 69955,
    "downloads": "5M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.com.rededor",
    "name": "Rede D'Or",
    "category": "Medicina",
    "icon": "/apps/rede-d-or.png",
    "rating": 4.9,
    "reviews": 9145,
    "downloads": "100K+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.com.gndi.beneficiario.gndieasy",
    "name": "Hapvida NotreDame",
    "category": "Medicina",
    "icon": "/apps/hapvida-notredame.png",
    "rating": 4,
    "reviews": 223117,
    "downloads": "5M+",
    "pain": 40,
    "trend": "—"
  },
  {
    "id": "br.com.beneficiario.odontoprev",
    "name": "Odontoprev",
    "category": "Medicina",
    "icon": "/apps/odontoprev.png",
    "rating": 4.5,
    "reviews": 21131,
    "downloads": "1M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.kaizengaming.betano.brazil",
    "name": "Betano: Apostas e Cassino",
    "category": "Esportes",
    "icon": "/apps/betano-apostas-e-cassino.png",
    "rating": 4.8,
    "reviews": 242225,
    "downloads": "5M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "eu.livesport.FlashScore_com",
    "name": "Flashscore: Resultados ao Vivo",
    "category": "Esportes",
    "icon": "/apps/flashscore-resultados-ao-vivo.png",
    "rating": 4.8,
    "reviews": 2380695,
    "downloads": "50M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.bet.betnacional",
    "name": "Betnacional Apostas Esportivas",
    "category": "Esportes",
    "icon": "/apps/betnacional-apostas-esportivas.png",
    "rating": 4.7,
    "reviews": 98155,
    "downloads": "1M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "com.bet365SportsBR.Bet365_Application",
    "name": "bet365 Apostas Esportivas",
    "category": "Esportes",
    "icon": "/apps/bet365-apostas-esportivas.png",
    "rating": 4.6,
    "reviews": 149680,
    "downloads": "1M+",
    "pain": 30,
    "trend": "—"
  },
  {
    "id": "br.bet.betmgm",
    "name": "BetMGM Apostas & Cassino",
    "category": "Esportes",
    "icon": "/apps/betmgm-apostas-cassino.png",
    "rating": 3.4,
    "reviews": 1465,
    "downloads": "500K+",
    "pain": 53,
    "trend": "—"
  }
];
